import type { ActivityEvent, Blog } from "@/types/blog";

// Shared mock fixtures for the UI phases. Phase 7 swaps the hooks that
// read these for real API calls; the shapes match the spec's Blog model.

function daysAgo(n: number, hours = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(d.getHours() - hours);
  return d.toISOString();
}

export const mockBlogs: Blog[] = [
  {
    id: "b1",
    title: "Understanding React Server Components",
    subtitle: "What actually runs where, and why it matters",
    category: "React",
    tags: ["react", "rsc", "nextjs"],
    status: "published",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(0, 2),
    publishedAt: daysAgo(0, 2),
    tokensUsed: 9_420,
    readingTime: 8,
    seoScore: 92,
    views: 1_840,
  },
  {
    id: "b2",
    title: "Next.js 15 Migration Guide",
    subtitle: "A checklist for upgrading real apps",
    category: "Next.js",
    tags: ["nextjs", "migration"],
    status: "draft",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    publishedAt: null,
    tokensUsed: 11_030,
    readingTime: 11,
    seoScore: 74,
    views: 0,
  },
  {
    id: "b3",
    title: "TypeScript Generics, Explained Simply",
    subtitle: "From <T> to conditional types without the headache",
    category: "TypeScript",
    tags: ["typescript", "generics"],
    status: "draft",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
    publishedAt: null,
    tokensUsed: 7_610,
    readingTime: 9,
    seoScore: 81,
    views: 0,
  },
  {
    id: "b4",
    title: "How I Prepared for My Frontend Interview at a FAANG",
    subtitle: "A 6-week plan that actually worked",
    category: "Career",
    tags: ["interview", "career"],
    status: "published",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
    publishedAt: daysAgo(10),
    tokensUsed: 12_480,
    readingTime: 12,
    seoScore: 88,
    views: 4_930,
  },
  {
    id: "b5",
    title: "The Practical Guide to Prompt Engineering",
    subtitle: "Patterns that survive contact with production",
    category: "AI",
    tags: ["ai", "prompts", "llm"],
    status: "published",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(15),
    publishedAt: daysAgo(15),
    tokensUsed: 10_950,
    readingTime: 10,
    seoScore: 95,
    views: 7_215,
  },
  {
    id: "b6",
    title: "Vue vs React in 2026: An Honest Comparison",
    subtitle: "Where each one still wins",
    category: "JavaScript",
    tags: ["vue", "react", "comparison"],
    status: "scheduled",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    publishedAt: null,
    tokensUsed: 9_870,
    readingTime: 9,
    seoScore: 86,
    views: 0,
  },
  {
    id: "b7",
    title: "10 VS Code Extensions That Changed How I Write Code",
    subtitle: "A listicle with receipts",
    category: "Productivity",
    tags: ["vscode", "tools", "productivity"],
    status: "published",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(24),
    publishedAt: daysAgo(24),
    tokensUsed: 6_540,
    readingTime: 6,
    seoScore: 79,
    views: 12_402,
  },
  {
    id: "b8",
    title: "Building a Design System with Tailwind v4",
    subtitle: "Tokens, themes, and the utilities in between",
    category: "CSS",
    tags: ["tailwind", "design-systems"],
    status: "draft",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(5),
    publishedAt: null,
    tokensUsed: 8_120,
    readingTime: 10,
    seoScore: 68,
    views: 0,
  },
];

export const mockActivity: ActivityEvent[] = [
  {
    id: "a1",
    type: "published",
    text: "Published “Understanding React Server Components”",
    at: daysAgo(0, 2),
  },
  {
    id: "a2",
    type: "generated",
    text: "Generated draft “Next.js 15 Migration Guide”",
    at: daysAgo(1),
  },
  {
    id: "a3",
    type: "edited",
    text: "Edited “TypeScript Generics, Explained Simply”",
    at: daysAgo(2),
  },
  {
    id: "a4",
    type: "connected",
    text: "Connected Medium account",
    at: daysAgo(3),
  },
  {
    id: "a5",
    type: "generated",
    text: "Generated draft “Building a Design System with Tailwind v4”",
    at: daysAgo(5),
  },
];
